// Generated by CoffeeScript 1.4.0
var Entity;

module.exports = Entity = (function() {

  function Entity() {}

  Entity.prototype["class"] = function() {};

  Entity.prototype.description = function() {};

  return Entity;

})();
